### ISSUE TITLE
Fails to install with UnicodeDecodeError exception

### ISSUE THREAD

**Issue by liquidsunshine** [nad2000/W3C-Validator#3]
Windows 10, Python 3.6

If my investigation is correct, it looks like the description from README.rst gets pulled into PKG-INFO when it gets built for PyPi.  Since README.rst includes special characters (the fancy quotes in the W3C validator output) that can't be decoded to cp1252 (the default Windows character encoding) setuptools blows up.  

There are some bugs open against setuptools/pip, but in the meantime this package is uninstallable from PyPi, at least on Windows.  A simple fix would be changing the special quote characters to regular quote characters in README.rst. 

Using pip 18.0:
```(venv) C:\Users\username\project>pip install Online-W3C-Validator
Collecting Online-W3C-Validator
  Using cached https://files.pythonhosted.org/packages/e0/fd/47252f627d60f8049c22f892bf53e6f39018664bf54a1798a9d4f1b7e218/Online-W3C-Validato
r-0.3.11.tar.gz
    Complete output from command python setup.py egg_info:
    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "C:\Users\username\project\venv\lib\site-packages\pbr\core.py", line 96, in pbr
        attrs = util.cfg_to_args(path, dist.script_args)
      File "C:\Users\username\project\venv\lib\site-packages\pbr\util.py", line 259, in cfg_to_args
        pbr.hooks.setup_hook(config)
      File "C:\Users\username\project\venv\lib\site-packages\pbr\hooks\__init__.py", line 25, in setup_hook
        metadata_config.run()
      File "C:\Users\username\project\venv\lib\site-packages\pbr\hooks\base.py", line 27, in run
        self.hook()
      File "C:\Users\username\project\venv\lib\site-packages\pbr\hooks\metadata.py", line 26, in hook
        self.config['name'], self.config.get('version', None))
      File "C:\Users\username\project\venv\lib\site-packages\pbr\packaging.py", line 821, in get_version
        version = _get_version_from_pkg_metadata(package_name)
      File "C:\Users\username\project\venv\lib\site-packages\pbr\packaging.py", line 789, in _get_version_from_pk
g_metadata
        pkg_metadata = email.message_from_file(pkg_metadata_file)
      File "C:\ProgramData\Anaconda3\lib\email\__init__.py", line 54, in message_from_file
        return Parser(*args, **kws).parse(fp)
      File "C:\ProgramData\Anaconda3\lib\email\parser.py", line 54, in parse
        data = fp.read(8192)
      File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1157: character maps to <undefined>
    error in setup command: Error parsing C:\Users\username\AppData\Local\Temp\pip-install-2kthxzaa\Online-W3C-Validator\setup.cfg: UnicodeDe
codeError: 'charmap' codec can't decode byte 0x9d in position 1157: character maps to <undefined>

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\username\AppData\Local\Temp\pip-install-2kthxzaa\Online-W3C-Validator
\
```

Using easy_install in setuptools 40.0.0:
```(venv) C:\Users\username\project>easy_install Online-W3C-Validator
Searching for Online-W3C-Validator
Reading https://pypi.org/simple/Online-W3C-Validator/
Downloading https://files.pythonhosted.org/packages/e0/fd/47252f627d60f8049c22f892bf53e6f39018664bf54a1798a9d4f1b7e218/Online-W3C-Validator-0
.3.11.tar.gz#sha256=68defd173435fb4d21d03e46e1bc967a7af7b42e72fb949b31d4a77da5d50f10
Best match: Online-W3C-Validator 0.3.11
Processing Online-W3C-Validator-0.3.11.tar.gz
Writing C:\Users\username\AppData\Local\Temp\easy_install-v_ec__to\Online-W3C-Validator-0.3.11\setup.cfg
Running Online-W3C-Validator-0.3.11\setup.py -q bdist_egg --dist-dir C:\Users\username\AppData\Local\Temp\easy_install-v_ec__to\Online-W3C-Va
lidator-0.3.11\egg-dist-tmp-1v642wnc
ERROR:root:Error parsing
Traceback (most recent call last):
  File "c:\users\username\project\venv\lib\site-packages\pbr\core.py", line 96, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "c:\users\username\project\venv\lib\site-packages\pbr\util.py", line 259, in cfg_to_args
    pbr.hooks.setup_hook(config)
  File "c:\users\username\project\venv\lib\site-packages\pbr\hooks\__init__.py", line 25, in setup_hook
    metadata_config.run()
  File "c:\users\username\project\venv\lib\site-packages\pbr\hooks\base.py", line 27, in run
    self.hook()
  File "c:\users\username\project\venv\lib\site-packages\pbr\hooks\metadata.py", line 26, in hook
    self.config['name'], self.config.get('version', None))
  File "c:\users\username\project\venv\lib\site-packages\pbr\packaging.py", line 821, in get_version
    version = _get_version_from_pkg_metadata(package_name)
  File "c:\users\username\project\venv\lib\site-packages\pbr\packaging.py", line 789, in _get_version_from_pkg_me
tadata
    pkg_metadata = email.message_from_file(pkg_metadata_file)
  File "C:\ProgramData\Anaconda3\lib\email\__init__.py", line 54, in message_from_file
    return Parser(*args, **kws).parse(fp)
  File "C:\ProgramData\Anaconda3\lib\email\parser.py", line 54, in parse
    data = fp.read(8192)
  File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1157: character maps to <undefined>
error: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\username\\AppData\\Local\\Te
mp\\easy_install-v_ec__to\\Online-W3C-Validator-0.3.11\\PKG-INFO'
```

**Comment by munchkin09** [comment]
> 
> 
> Windows 10, Python 3.6
> 
> If my investigation is correct, it looks like the description from README.rst gets pulled into PKG-INFO when it gets built for PyPi. Since README.rst includes special characters (the fancy quotes in the W3C validator output) that can't be decoded to cp1252 (the default Windows character encoding) setuptools blows up.
> 
> There are some bugs open against setuptools/pip, but in the meantime this package is uninstallable from PyPi, at least on Windows. A simple fix would be changing the special quote characters to regular quote characters in README.rst.
> 
> Using pip 18.0:
> 
> ```
> Collecting Online-W3C-Validator
>   Using cached https://files.pythonhosted.org/packages/e0/fd/47252f627d60f8049c22f892bf53e6f39018664bf54a1798a9d4f1b7e218/Online-W3C-Validato
> r-0.3.11.tar.gz
>     Complete output from command python setup.py egg_info:
>     ERROR:root:Error parsing
>     Traceback (most recent call last):
>       File "C:\Users\username\project\venv\lib\site-packages\pbr\core.py", line 96, in pbr
>         attrs = util.cfg_to_args(path, dist.script_args)
>       File "C:\Users\username\project\venv\lib\site-packages\pbr\util.py", line 259, in cfg_to_args
>         pbr.hooks.setup_hook(config)
>       File "C:\Users\username\project\venv\lib\site-packages\pbr\hooks\__init__.py", line 25, in setup_hook
>         metadata_config.run()
>       File "C:\Users\username\project\venv\lib\site-packages\pbr\hooks\base.py", line 27, in run
>         self.hook()
>       File "C:\Users\username\project\venv\lib\site-packages\pbr\hooks\metadata.py", line 26, in hook
>         self.config['name'], self.config.get('version', None))
>       File "C:\Users\username\project\venv\lib\site-packages\pbr\packaging.py", line 821, in get_version
>         version = _get_version_from_pkg_metadata(package_name)
>       File "C:\Users\username\project\venv\lib\site-packages\pbr\packaging.py", line 789, in _get_version_from_pk
> g_metadata
>         pkg_metadata = email.message_from_file(pkg_metadata_file)
>       File "C:\ProgramData\Anaconda3\lib\email\__init__.py", line 54, in message_from_file
>         return Parser(*args, **kws).parse(fp)
>       File "C:\ProgramData\Anaconda3\lib\email\parser.py", line 54, in parse
>         data = fp.read(8192)
>       File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
>         return codecs.charmap_decode(input,self.errors,decoding_table)[0]
>     UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1157: character maps to <undefined>
>     error in setup command: Error parsing C:\Users\username\AppData\Local\Temp\pip-install-2kthxzaa\Online-W3C-Validator\setup.cfg: UnicodeDe
> codeError: 'charmap' codec can't decode byte 0x9d in position 1157: character maps to <undefined>
> 
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in C:\Users\username\AppData\Local\Temp\pip-install-2kthxzaa\Online-W3C-Validator
> \
> ```
> 
> Using easy_install in setuptools 40.0.0:
> 
> ```
> Searching for Online-W3C-Validator
> Reading https://pypi.org/simple/Online-W3C-Validator/
> Downloading https://files.pythonhosted.org/packages/e0/fd/47252f627d60f8049c22f892bf53e6f39018664bf54a1798a9d4f1b7e218/Online-W3C-Validator-0
> .3.11.tar.gz#sha256=68defd173435fb4d21d03e46e1bc967a7af7b42e72fb949b31d4a77da5d50f10
> Best match: Online-W3C-Validator 0.3.11
> Processing Online-W3C-Validator-0.3.11.tar.gz
> Writing C:\Users\username\AppData\Local\Temp\easy_install-v_ec__to\Online-W3C-Validator-0.3.11\setup.cfg
> Running Online-W3C-Validator-0.3.11\setup.py -q bdist_egg --dist-dir C:\Users\username\AppData\Local\Temp\easy_install-v_ec__to\Online-W3C-Va
> lidator-0.3.11\egg-dist-tmp-1v642wnc
> ERROR:root:Error parsing
> Traceback (most recent call last):
>   File "c:\users\username\project\venv\lib\site-packages\pbr\core.py", line 96, in pbr
>     attrs = util.cfg_to_args(path, dist.script_args)
>   File "c:\users\username\project\venv\lib\site-packages\pbr\util.py", line 259, in cfg_to_args
>     pbr.hooks.setup_hook(config)
>   File "c:\users\username\project\venv\lib\site-packages\pbr\hooks\__init__.py", line 25, in setup_hook
>     metadata_config.run()
>   File "c:\users\username\project\venv\lib\site-packages\pbr\hooks\base.py", line 27, in run
>     self.hook()
>   File "c:\users\username\project\venv\lib\site-packages\pbr\hooks\metadata.py", line 26, in hook
>     self.config['name'], self.config.get('version', None))
>   File "c:\users\username\project\venv\lib\site-packages\pbr\packaging.py", line 821, in get_version
>     version = _get_version_from_pkg_metadata(package_name)
>   File "c:\users\username\project\venv\lib\site-packages\pbr\packaging.py", line 789, in _get_version_from_pkg_me
> tadata
>     pkg_metadata = email.message_from_file(pkg_metadata_file)
>   File "C:\ProgramData\Anaconda3\lib\email\__init__.py", line 54, in message_from_file
>     return Parser(*args, **kws).parse(fp)
>   File "C:\ProgramData\Anaconda3\lib\email\parser.py", line 54, in parse
>     data = fp.read(8192)
>   File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
>     return codecs.charmap_decode(input,self.errors,decoding_table)[0]
> UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1157: character maps to <undefined>
> error: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\username\\AppData\\Local\\Te
> mp\\easy_install-v_ec__to\\Online-W3C-Validator-0.3.11\\PKG-INFO'
> ```

+1
