### ISSUE TITLE
validating locally saved files

### ISSUE THREAD

**Issue by ptoche** [nad2000/W3C-Validator#4]
Is it possible to validate locally saved files?

I tried:

    from w3c_validator import validate
    file = '/path/to/file.xhtml' 
    with open(file, encoding='utf8') as infile:
        # print(infile.readlines()[:10])  # check that the file is properly opened
        messages = validate(infile)["messages"]
        for m in messages:
            print("Type: %(type)s, Line: %(lastLine)d, Description: %(message)s" % m)

    Traceback (most recent call last):
      File "<stdin>", line 3, in <module>
      File "/Users/username/miniconda3/envs/vs/lib/python3.8/site-packages/w3c_validator/validator.py", line 41, in validate
        is_remote = filename.startswith("http://") or filename.startswith(
    AttributeError: '_io.TextIOWrapper' object has no attribute 'startswith'

**Comment by HundredVisionsGuy** [comment]
I was working on my own python validator code before I came across this, and I don't know how I would incorporate my code into this codebase, but here is my code that sends a local file to the validator API and captures the response as a JSON object then converts it to a list. I'm using the requests and json library:
```
import requests
import json 

w3cURL = 'https://validator.w3.org/nu/?out=json'
errors = []
payload = open(filepath)
with open(filepath,'rb') as payload:
      headers = {'content-type': 'text/html; charset=utf-8', 'Accept-Charset': 'UTF-8'}
      r = requests.post(w3cURL, data=payload, headers=headers)
      errors = r.json()['messages']
```

As you'll note, I'm not using this library, but if I have the time, I would be more than willing to help attempt this using the W3C-Validator library and do a pull request on the documentation.

**Comment by ptoche** [comment]
Thanks for sharing!
