### ISSUE TITLE
Error when trying to install the library through PIP

### ISSUE THREAD

**Issue by Yoseph-Reyes** [nad2000/W3C-Validator#6]
Hello, I get this error when I try to install the library

`Python311\Lib\site-packages\setuptools\installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      WARNING: The wheel package is not available.
      Error parsing
      Traceback (most recent call last):
        File "c:\users\usuario\appdata\local\temp\pip-install-ou6hxccx\online-w3c-validator_f7de448c7c074fcd8c92b5a1a95fc803\.eggs\pbr-5.11.1-py3.11.egg\pbr\core.py", line 105, in pbr
          attrs = util.cfg_to_args(path, dist.script_args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "c:\users\usuario\appdata\local\temp\pip-install-ou6hxccx\online-w3c-validator_f7de448c7c074fcd8c92b5a1a95fc803\.eggs\pbr-5.11.1-py3.11.egg\pbr\util.py", line 272, in cfg_to_args
          pbr.hooks.setup_hook(config)
        File "c:\users\usuario\appdata\local\temp\pip-install-ou6hxccx\online-w3c-validator_f7de448c7c074fcd8c92b5a1a95fc803\.eggs\pbr-5.11.1-py3.11.egg\pbr\hooks\__init__.py", line 25, in setup_hook
          metadata_config.run()
        File "c:\users\usuario\appdata\local\temp\pip-install-ou6hxccx\online-w3c-validator_f7de448c7c074fcd8c92b5a1a95fc803\.eggs\pbr-5.11.1-py3.11.egg\pbr\hooks\base.py", line 27, in run
          self.hook()
        File "c:\users\usuario\appdata\local\temp\pip-install-ou6hxccx\online-w3c-validator_f7de448c7c074fcd8c92b5a1a95fc803\.eggs\pbr-5.11.1-py3.11.egg\pbr\hooks\metadata.py", line 25, in hook
          self.config['version'] = packaging.get_version(
                                   ^^^^^^^^^^^^^^^^^^^^^^
        File "c:\users\usuario\appdata\local\temp\pip-install-ou6hxccx\online-w3c-validator_f7de448c7c074fcd8c92b5a1a95fc803\.eggs\pbr-5.11.1-py3.11.egg\pbr\packaging.py", line 862, in get_version
          version = _get_version_from_pkg_metadata(package_name)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "c:\users\usuario\appdata\local\temp\pip-install-ou6hxccx\online-w3c-validator_f7de448c7c074fcd8c92b5a1a95fc803\.eggs\pbr-5.11.1-py3.11.egg\pbr\packaging.py", line 830, in _get_version_from_pkg_metadata
          pkg_metadata = email.message_from_file(pkg_metadata_file)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\USUARIO\AppData\Local\Programs\Python\Python311\Lib\email\__init__.py", line 54, in message_from_file
          return Parser(*args, **kws).parse(fp)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\USUARIO\AppData\Local\Programs\Python\Python311\Lib\email\parser.py", line 53, in parse
          data = fp.read(8192)
                 ^^^^^^^^^^^^^
        File "C:\Users\USUARIO\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1737: character maps to <undefined>
      error in setup command: Error parsing C:\Users\USUARIO\AppData\Local\Temp\pip-install-ou6hxccx\online-w3c-validator_f7de448c7c074fcd8c92b5a1a95fc803\setup.cfg: UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1737: character maps to <undefined>
      [end of output]`

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by Makwana-Bharat** [comment]
i also get same error

pip install -U Online-W3C-Validator
Collecting Online-W3C-Validator
  Using cached Online-W3C-Validator-0.3.21.tar.gz (77 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      Error parsing
      Traceback (most recent call last):
        File "...\AppData\Local\Temp\pip-build-env-yptct9bq\normal\Lib\site-packages\pbr\core.py", line 105, in pbr
          attrs = util.cfg_to_args(path, dist.script_args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "...\AppData\Local\Temp\pip-build-env-yptct9bq\normal\Lib\site-packages\pbr\util.py", line 272, in cfg_to_args
          pbr.hooks.setup_hook(config)
        File "...\AppData\Local\Temp\pip-build-env-yptct9bq\normal\Lib\site-packages\pbr\hooks\__init__.py", line 25, in setup_hook
          metadata_config.run()
        File "...\AppData\Local\Temp\pip-build-env-yptct9bq\normal\Lib\site-packages\pbr\hooks\base.py", line 27, in run
          self.hook()
        File "...\AppData\Local\Temp\pip-build-env-yptct9bq\normal\Lib\site-packages\pbr\hooks\metadata.py", line 25, in hook
          self.config['version'] = packaging.get_version(
                                   ^^^^^^^^^^^^^^^^^^^^^^
        File "...\AppData\Local\Temp\pip-build-env-yptct9bq\normal\Lib\site-packages\pbr\packaging.py", line 862, in get_version
          version = _get_version_from_pkg_metadata(package_name)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "...\AppData\Local\Temp\pip-build-env-yptct9bq\normal\Lib\site-packages\pbr\packaging.py", line 830, in _get_version_from_pkg_metadata
          pkg_metadata = email.message_from_file(pkg_metadata_file)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "...\AppData\Local\Programs\Python\Python311\Lib\email\__init__.py", line 54, in message_from_file
          return Parser(*args, **kws).parse(fp)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "...\AppData\Local\Programs\Python\Python311\Lib\email\parser.py", line 53, in parse
          data = fp.read(8192)
                 ^^^^^^^^^^^^^
        File "...\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1753: character maps to <undefined>
      error in setup command: Error parsing ...\AppData\Local\Temp\pip-install-ofxq7n87\online-w3c-validator_2a2c81db17914d328200cea924d674e3\setup.cfg: UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1753: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by hype8912** [comment]
On a Windows computer set the following environment variable and the package will install correctly.
`PYTHONUTF8=1`

Reference to information. https://stackoverflow.com/questions/49640513/unicodedecodeerror-charmap-codec-cant-decode-byte-0x9d-in-position-x-charac/70923999#70923999

**Comment by Nagidrop** [comment]
As @hype8912 mentioned, setting environment variable `PYTHONUTF8=1` fixes the issue.

It can be set in JupyterLab using this line:
```
%env PYTHONUTF8 1
```
